import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { Button, ButtonLink } from "../../components/ui/Button";
import { Card, CardContent, CardHeader } from "../../components/ui/Card";
import { EmptyState } from "../../components/ui/EmptyState";
import { ErrorState } from "../../components/ui/ErrorState";
import { LoadingState } from "../../components/ui/LoadingState";
import { useAuth } from "../../hooks/useAuth";
import { generateSyntheticDataset, getPrivacyDoctorOverview } from "./api";
import { DatasetStatusBadge } from "./components/DatasetStatusBadge";
import { RiskBandBadge } from "./components/RiskBandBadge";
import type { PrivacyDoctorOverview } from "./types";

function MetricCard({
  label,
  value,
  tone = "neutral",
}: {
  label: string;
  value: number | string;
  tone?: "neutral" | "rose" | "amber" | "teal" | "sage" | "blue";
}) {
  const toneMap: Record<string, string> = {
    neutral: "border-paper-line bg-paper-card",
    rose:    "border-civic-rose/30 bg-civic-rose/5",
    amber:   "border-civic-amber/30 bg-civic-amber/5",
    teal:    "border-civic-teal/30 bg-civic-teal/5",
    sage:    "border-civic-sage/30 bg-civic-sage/5",
    blue:    "border-civic-blue/30 bg-civic-blue/5",
  };
  const valueMap: Record<string, string> = {
    neutral: value === 0 ? "text-ink-soft" : "text-ink",
    rose:    "text-rose-ink",
    amber:   "text-gold-ink",
    teal:    "text-orange-ink",
    sage:    "text-sage-ink",
    blue:    "text-bluec-ink",
  };
  return (
    <div className={`rounded-lg border p-4 ${toneMap[tone]}`}>
      <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">{label}</p>
      <p className={`mt-2 font-display text-2xl font-bold tabular-nums ${valueMap[tone]}`}>{value}</p>
    </div>
  );
}

export function PrivacyDoctorOverviewPage() {
  const { user } = useAuth();
  const [overview, setOverview] = useState<PrivacyDoctorOverview | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [actionMsg, setActionMsg] = useState<string | null>(null);
  const [isActing, setIsActing] = useState(false);

  const canAct = user?.role === "admin" || user?.role === "analyst";

  const loadOverview = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      setOverview(await getPrivacyDoctorOverview());
    } catch {
      setError("Could not load DataPrivacy Doctor overview. Is the backend running?");
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadOverview();
  }, [loadOverview]);

  async function handleGenerateSynthetic() {
    setIsActing(true);
    setActionMsg(null);
    try {
      const result = await generateSyntheticDataset(60);
      setActionMsg(
        `Synthetic dataset generated — ${result.row_count} rows, risk score ${result.privacy_risk_score}/100 (${result.risk_band}). ` +
          `${result.findings_created} finding(s) detected.`,
      );
      void loadOverview();
    } catch {
      setActionMsg("Failed to generate synthetic dataset.");
    } finally {
      setIsActing(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-xl font-semibold text-ink">DataPrivacy Doctor</h1>
          <p className="mt-0.5 text-sm text-ink-soft">
            CSV privacy analysis — identify direct identifiers, quasi-identifiers, and sensitive
            attributes.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <ButtonLink to="/modules/privacy-doctor/datasets" variant="secondary">
            All Datasets
          </ButtonLink>
          {canAct && (
            <ButtonLink to="/modules/privacy-doctor/upload" variant="primary">
              Upload Dataset
            </ButtonLink>
          )}
        </div>
      </div>

      {/* Responsible-use note */}
      <div className="rounded-lg border border-paper-line bg-paper-card/60 px-4 py-3 text-xs text-ink-soft">
        <span className="font-medium text-ink">Human review required. </span>
        DataPrivacy Doctor outputs are decision-support signals generated by automated heuristics.
        All findings require verification by a qualified data protection officer before any action
        is taken. This tool does not constitute legal advice.
      </div>

      {/* Analyst actions */}
      {canAct && (
        <div className="flex flex-wrap items-center gap-3">
          <Button
            variant="primary"
            disabled={isActing}
            onClick={() => void handleGenerateSynthetic()}
          >
            {isActing ? "Generating…" : "Generate Synthetic Dataset"}
          </Button>
          {actionMsg && <span className="text-xs text-ink-soft">{actionMsg}</span>}
        </div>
      )}

      {isLoading && <LoadingState label="Loading DataPrivacy Doctor" />}
      {error && <ErrorState message={error} />}

      {overview && !isLoading && (
        <>
          {/* Metrics */}
          <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
            <MetricCard label="Total Datasets" value={overview.total_datasets} />
            <MetricCard label="Fully Scanned" value={overview.complete_datasets} tone="sage" />
            <MetricCard
              label="High / Severe Risk"
              value={overview.high_risk_datasets}
              tone={overview.high_risk_datasets > 0 ? "rose" : "neutral"}
            />
            <MetricCard
              label="Severe Risk"
              value={overview.severe_risk_datasets}
              tone={overview.severe_risk_datasets > 0 ? "rose" : "neutral"}
            />
            <MetricCard
              label="Contain Direct Identifiers"
              value={overview.datasets_with_identifiers}
              tone={overview.datasets_with_identifiers > 0 ? "amber" : "neutral"}
            />
            <MetricCard
              label="Contain Sensitive Attributes"
              value={overview.datasets_with_sensitive}
              tone={overview.datasets_with_sensitive > 0 ? "blue" : "neutral"}
            />
          </section>

          {/* Recent datasets */}
          {overview.recent_datasets.length > 0 ? (
            <Card>
              <CardHeader
                title="Recent Datasets"
                action={
                  <Link
                    to="/modules/privacy-doctor/datasets"
                    className="text-xs font-medium text-ink-soft transition-colors hover:text-orange-ink"
                  >
                    View all →
                  </Link>
                }
              />
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="border-b border-paper-line text-xs uppercase tracking-wide text-ink-soft">
                      <tr>
                        <th className="px-4 py-2 text-left">File</th>
                        <th className="px-4 py-2 text-right">Rows</th>
                        <th className="px-4 py-2 text-right">Cols</th>
                        <th className="px-4 py-2 text-center">Risk Band</th>
                        <th className="px-4 py-2 text-center">Status</th>
                        <th className="px-4 py-2 text-right">Findings</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-paper-line">
                      {overview.recent_datasets.map((ds) => (
                        <tr key={ds.id} className="transition-colors hover:bg-paper-raise">
                          <td className="px-4 py-2">
                            <Link
                              to={`/modules/privacy-doctor/datasets/${ds.id}`}
                              className="font-medium text-ink transition-colors hover:text-orange-ink"
                            >
                              {ds.original_filename}
                            </Link>
                          </td>
                          <td className="px-4 py-2 text-right tabular-nums text-ink-soft">
                            {ds.row_count.toLocaleString()}
                          </td>
                          <td className="px-4 py-2 text-right tabular-nums text-ink-soft">
                            {ds.column_count}
                          </td>
                          <td className="px-4 py-2 text-center">
                            {ds.risk_band ? (
                              <RiskBandBadge band={ds.risk_band} score={ds.privacy_risk_score} />
                            ) : (
                              <span className="text-ink-soft">—</span>
                            )}
                          </td>
                          <td className="px-4 py-2 text-center">
                            <DatasetStatusBadge
                              status={ds.processing_status}
                              label={ds.processing_status_display}
                            />
                          </td>
                          <td className="px-4 py-2 text-right tabular-nums text-ink-soft">
                            {ds.finding_count}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          ) : (
            overview.total_datasets === 0 && (
              <EmptyState
                title="No datasets scanned yet"
                description={
                  canAct
                    ? "Upload a CSV or generate a synthetic demo dataset to get started."
                    : undefined
                }
              />
            )
          )}
        </>
      )}
    </div>
  );
}
