import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { useAuth } from "../../hooks/useAuth";
import { generateSyntheticDataset, getPrivacyDoctorOverview } from "./api";
import { DatasetStatusBadge } from "./components/DatasetStatusBadge";
import { RiskBandBadge } from "./components/RiskBandBadge";
import type { PrivacyDoctorOverview } from "./types";

function MetricCard({
  label,
  value,
  tone = "neutral",
}: {
  label: string;
  value: number | string;
  tone?: "neutral" | "rose" | "amber" | "green" | "purple";
}) {
  const toneClasses: Record<string, string> = {
    neutral: "border-neutral-700 bg-neutral-900",
    rose: "border-rose-800 bg-rose-950/40",
    amber: "border-amber-800 bg-amber-950/40",
    green: "border-green-800 bg-green-950/40",
    purple: "border-purple-800 bg-purple-950/40",
  };
  const valueClasses: Record<string, string> = {
    neutral: "text-neutral-100",
    rose: "text-rose-300",
    amber: "text-amber-300",
    green: "text-green-300",
    purple: "text-purple-300",
  };
  return (
    <div className={`rounded-lg border p-4 ${toneClasses[tone]}`}>
      <p className="text-xs font-medium uppercase tracking-wide text-neutral-400">{label}</p>
      <p className={`mt-2 text-2xl font-bold tabular-nums ${valueClasses[tone]}`}>{value}</p>
    </div>
  );
}

export function PrivacyDoctorOverviewPage() {
  const { user } = useAuth();
  const [overview, setOverview] = useState<PrivacyDoctorOverview | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [actionMsg, setActionMsg] = useState<string | null>(null);
  const [isActing, setIsActing] = useState(false);

  const canAct = user?.role === "admin" || user?.role === "analyst";

  const loadOverview = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      setOverview(await getPrivacyDoctorOverview());
    } catch {
      setError("Could not load DataPrivacy Doctor overview. Is the backend running?");
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadOverview();
  }, [loadOverview]);

  async function handleGenerateSynthetic() {
    setIsActing(true);
    setActionMsg(null);
    try {
      const result = await generateSyntheticDataset(60);
      setActionMsg(
        `Synthetic dataset generated — ${result.row_count} rows, risk score ${result.privacy_risk_score}/100 (${result.risk_band}). ` +
          `${result.findings_created} finding(s) detected.`,
      );
      void loadOverview();
    } catch {
      setActionMsg("Failed to generate synthetic dataset.");
    } finally {
      setIsActing(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-semibold text-neutral-100">DataPrivacy Doctor</h1>
          <p className="mt-0.5 text-sm text-neutral-400">
            CSV privacy analysis — identify direct identifiers, quasi-identifiers, and sensitive
            attributes.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Link
            to="/modules/privacy-doctor/datasets"
            className="rounded-md border border-neutral-700 bg-neutral-800 px-3 py-1.5 text-xs font-medium text-neutral-200 hover:bg-neutral-700 transition-colors"
          >
            All Datasets
          </Link>
          {canAct && (
            <Link
              to="/modules/privacy-doctor/upload"
              className="rounded-md bg-blue-700 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-600 transition-colors"
            >
              Upload Dataset
            </Link>
          )}
        </div>
      </div>

      {/* Responsible-use note */}
      <div className="rounded-lg border border-neutral-800 bg-neutral-900/50 px-4 py-3 text-xs text-neutral-500">
        <span className="font-medium text-neutral-400">Human review required. </span>
        DataPrivacy Doctor outputs are decision-support signals generated by automated heuristics.
        All findings require verification by a qualified data protection officer before any action
        is taken. This tool does not constitute legal advice.
      </div>

      {/* Analyst actions */}
      {canAct && (
        <div className="flex flex-wrap items-center gap-3">
          <button
            disabled={isActing}
            onClick={() => void handleGenerateSynthetic()}
            className="rounded-md bg-emerald-700 px-3 py-1.5 text-xs font-medium text-white hover:bg-emerald-600 disabled:opacity-50 transition-colors"
          >
            {isActing ? "Generating…" : "Generate Synthetic Dataset"}
          </button>
          {actionMsg && <span className="text-xs text-neutral-400">{actionMsg}</span>}
        </div>
      )}

      {isLoading && (
        <div className="py-12 text-center text-sm text-neutral-500">
          Loading DataPrivacy Doctor…
        </div>
      )}
      {error && (
        <div className="rounded-lg border border-rose-800 bg-rose-950/40 px-4 py-3 text-sm text-rose-300">
          {error}
        </div>
      )}

      {overview && !isLoading && (
        <>
          {/* Metrics */}
          <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
            <MetricCard label="Total Datasets" value={overview.total_datasets} />
            <MetricCard label="Fully Scanned" value={overview.complete_datasets} tone="green" />
            <MetricCard
              label="High / Severe Risk"
              value={overview.high_risk_datasets}
              tone={overview.high_risk_datasets > 0 ? "rose" : "neutral"}
            />
            <MetricCard
              label="Severe Risk"
              value={overview.severe_risk_datasets}
              tone={overview.severe_risk_datasets > 0 ? "rose" : "neutral"}
            />
            <MetricCard
              label="Contain Direct Identifiers"
              value={overview.datasets_with_identifiers}
              tone={overview.datasets_with_identifiers > 0 ? "amber" : "neutral"}
            />
            <MetricCard
              label="Contain Sensitive Attributes"
              value={overview.datasets_with_sensitive}
              tone={overview.datasets_with_sensitive > 0 ? "purple" : "neutral"}
            />
          </section>

          {/* Recent datasets */}
          {overview.recent_datasets.length > 0 && (
            <section>
              <div className="mb-3 flex items-center justify-between">
                <h2 className="text-sm font-semibold text-neutral-300">Recent Datasets</h2>
                <Link
                  to="/modules/privacy-doctor/datasets"
                  className="text-xs text-blue-400 hover:text-blue-300"
                >
                  View all →
                </Link>
              </div>
              <div className="overflow-x-auto rounded-lg border border-neutral-800">
                <table className="w-full text-sm">
                  <thead className="border-b border-neutral-800 bg-neutral-900/80 text-xs uppercase tracking-wide text-neutral-500">
                    <tr>
                      <th className="px-4 py-2 text-left">File</th>
                      <th className="px-4 py-2 text-right">Rows</th>
                      <th className="px-4 py-2 text-right">Cols</th>
                      <th className="px-4 py-2 text-center">Risk Band</th>
                      <th className="px-4 py-2 text-center">Status</th>
                      <th className="px-4 py-2 text-right">Findings</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-neutral-800 bg-neutral-950">
                    {overview.recent_datasets.map((ds) => (
                      <tr key={ds.id} className="hover:bg-neutral-900/60 transition-colors">
                        <td className="px-4 py-2">
                          <Link
                            to={`/modules/privacy-doctor/datasets/${ds.id}`}
                            className="font-medium text-neutral-200 hover:text-blue-300 transition-colors"
                          >
                            {ds.original_filename}
                          </Link>
                        </td>
                        <td className="px-4 py-2 text-right tabular-nums text-neutral-400">
                          {ds.row_count.toLocaleString()}
                        </td>
                        <td className="px-4 py-2 text-right tabular-nums text-neutral-400">
                          {ds.column_count}
                        </td>
                        <td className="px-4 py-2 text-center">
                          {ds.risk_band ? (
                            <RiskBandBadge band={ds.risk_band} score={ds.privacy_risk_score} />
                          ) : (
                            <span className="text-neutral-600">—</span>
                          )}
                        </td>
                        <td className="px-4 py-2 text-center">
                          <DatasetStatusBadge
                            status={ds.processing_status}
                            label={ds.processing_status_display}
                          />
                        </td>
                        <td className="px-4 py-2 text-right tabular-nums text-neutral-400">
                          {ds.finding_count}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          )}

          {overview.total_datasets === 0 && (
            <div className="rounded-lg border border-dashed border-neutral-800 py-16 text-center">
              <p className="text-sm text-neutral-500">No datasets scanned yet.</p>
              {canAct && (
                <p className="mt-2 text-xs text-neutral-600">
                  Upload a CSV or generate a synthetic demo dataset to get started.
                </p>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
