"""IncidentFlow — Markdown incident report generator."""

from django.utils import timezone

from apps.incidents.models import Incident

SEVERITY_LABEL = {
    "low": "🟢 Low",
    "medium": "🟡 Medium",
    "high": "🔴 High",
    "critical": "🚨 Critical",
}

STATUS_LABEL = {
    "open": "Open",
    "investigating": "Investigating",
    "contained": "Contained",
    "resolved": "Resolved",
    "closed": "Closed",
    "dismissed": "Dismissed",
}

TASK_STATUS_SYMBOL = {
    "pending": "⬜",
    "in_progress": "🔄",
    "done": "✅",
    "skipped": "⏭️",
}

ENTRY_TYPE_LABEL = {
    "alert_created": "Alert Created",
    "status_changed": "Status Changed",
    "note_added": "Note Added",
    "action_completed": "Action Completed",
    "evidence_added": "Evidence Added",
    "report_generated": "Report Generated",
    "manual_update": "Update",
}


def generate_incident_report(incident: Incident) -> str:
    """Return a Markdown incident report as a string."""
    now = timezone.now().strftime("%Y-%m-%d %H:%M UTC")
    severity_label = SEVERITY_LABEL.get(incident.severity, incident.severity)
    status_label = STATUS_LABEL.get(incident.status, incident.status)
    tasks = list(incident.tasks.order_by("order", "created_at"))
    timeline = list(incident.timeline_entries.order_by("timestamp"))
    risk_events = list(incident.linked_risk_events.all())

    lines = [
        "# Incident Report",
        "",
        f"**{incident.title}**  ",
        f"**Organisation:** {incident.organisation.name}  ",
        f"**Report generated:** {now}  ",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Severity | {severity_label} |",
        f"| Status | {status_label} |",
        f"| Type | {incident.get_incident_type_display()} |",
        f"| Owner | {incident.owner.email if incident.owner else '—'} |",
        f"| Opened | {incident.opened_at.strftime('%Y-%m-%d %H:%M UTC')} |",
        f"| Closed | {incident.closed_at.strftime('%Y-%m-%d %H:%M UTC') if incident.closed_at else '—'} |",
        f"| Tasks | {len(tasks)} ({sum(1 for t in tasks if t.status == 'done')} done) |",
        "",
        "---",
        "",
        "## Description",
        "",
        incident.description or "*No description provided.*",
        "",
        "---",
        "",
        "## Response Tasks",
        "",
    ]

    if tasks:
        for task in tasks:
            symbol = TASK_STATUS_SYMBOL.get(task.status, "•")
            assignee = task.assignee.email if task.assignee else "Unassigned"
            lines.append(
                f"{symbol} **{task.title}** — _{task.get_status_display()}_ (assignee: {assignee})"
            )
            if task.description:
                lines.append(f"  > {task.description}")
            if task.notes:
                lines.append(f"  > Notes: {task.notes}")
            lines.append("")
    else:
        lines.append("*No tasks recorded.*")
        lines.append("")

    lines += [
        "---",
        "",
        "## Timeline",
        "",
    ]

    if timeline:
        for entry in timeline:
            ts = entry.timestamp.strftime("%Y-%m-%d %H:%M UTC")
            type_label = ENTRY_TYPE_LABEL.get(entry.entry_type, entry.entry_type)
            actor = entry.actor.email if entry.actor else "System"
            lines += [
                f"### {ts} — {type_label}",
                "",
                f"**{entry.title}**  ",
                f"_{actor}_  ",
                "",
            ]
            if entry.description:
                lines += [entry.description, ""]
    else:
        lines.append("*No timeline entries recorded.*")
        lines.append("")

    if risk_events:
        lines += [
            "---",
            "",
            "## Linked Risk Events",
            "",
        ]
        for re in risk_events:
            lines.append(f"- **{re.title}** (id: {re.id}, severity: {re.severity})")
        lines.append("")

    lines += [
        "---",
        "",
        "## Timeline Summary",
        "",
        incident.timeline_summary or "*No timeline summary provided.*",
        "",
        "---",
        "",
        "## Lessons Learned",
        "",
        incident.lessons_learned or "*Lessons learned not yet recorded.*",
        "",
        "---",
        "",
        "*Generated by CivicSec Lab — IncidentFlow. "
        "For internal use only. Do not distribute without review.*",
    ]

    return "\n".join(lines)
