# Generated by Django 5.2.15 on 2026-06-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misinformation", "0002_dataset_detected_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicpost",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="misinformation.narrativecluster",
            ),
        ),
    ]
