# Generated by Django 5.2.14 on 2026-06-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("risk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("column_count", models.PositiveIntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("delete_after_processing", "Delete after processing"),
                            ("retain_for_demo", "Retain for demo"),
                            ("manual_delete", "Manual delete"),
                        ],
                        default="delete_after_processing",
                        max_length=30,
                    ),
                ),
                ("original_file_deleted", models.BooleanField(default=False)),
                ("privacy_risk_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "risk_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low (0–20)"),
                            ("moderate", "Moderate (21–45)"),
                            ("high", "High (46–70)"),
                            ("severe", "Severe (71–100)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_datasets",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "risk_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_datasets",
                        to="risk.riskevent",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("direct_identifier_detected", "Direct identifier detected"),
                            ("quasi_identifier_combination", "Quasi-identifier combination"),
                            ("high_uniqueness_column", "High uniqueness column"),
                            ("sensitive_attribute_detected", "Sensitive attribute detected"),
                            ("risky_free_text", "Risky free text"),
                            (
                                "small_group_reidentification_risk",
                                "Small-group re-identification risk",
                            ),
                            ("excessive_data_collection", "Excessive data collection"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=0.8)),
                ("affected_columns", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=dict)),
                ("recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="privacy_doctor.uploadeddataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "finding_type"],
            },
        ),
        migrations.CreateModel(
            name="DatasetColumnProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("column_name", models.CharField(max_length=255)),
                (
                    "inferred_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("numeric", "Numeric"),
                            ("date", "Date"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("name", "Name"),
                            ("address", "Address"),
                            ("identifier", "Identifier"),
                            ("category", "Category"),
                            ("free_text", "Free text"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "privacy_category",
                    models.CharField(
                        choices=[
                            ("direct_identifier", "Direct identifier"),
                            ("quasi_identifier", "Quasi-identifier"),
                            ("sensitive_attribute", "Sensitive attribute"),
                            ("free_text_risk", "Free-text risk"),
                            ("low_risk", "Low risk"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=25,
                    ),
                ),
                ("uniqueness_ratio", models.FloatField(default=0.0)),
                ("missingness_ratio", models.FloatField(default=0.0)),
                ("sample_values_masked", models.JSONField(default=list)),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("recommended_transformation", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_profiles",
                        to="privacy_doctor.uploadeddataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score", "column_name"],
            },
        ),
        migrations.AddIndex(
            model_name="uploadeddataset",
            index=models.Index(
                fields=["organisation", "processing_status"], name="privacy_doc_organis_837686_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadeddataset",
            index=models.Index(
                fields=["organisation", "uploaded_at"], name="privacy_doc_organis_82cf19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyfinding",
            index=models.Index(
                fields=["dataset", "severity"], name="privacy_doc_dataset_f68264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyfinding",
            index=models.Index(
                fields=["dataset", "finding_type"], name="privacy_doc_dataset_d2c9b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datasetcolumnprofile",
            unique_together={("dataset", "column_name")},
        ),
    ]
