"""DataPrivacy Doctor — Markdown privacy report generator."""

from django.utils import timezone

from apps.privacy_doctor.models import UploadedDataset

RISK_BAND_LABELS = {
    "low": "🟢 Low",
    "moderate": "🟡 Moderate",
    "high": "🔴 High",
    "severe": "🔴 Severe",
}

SEVERITY_EMOJI = {
    "low": "🟢",
    "medium": "🟡",
    "high": "🔴",
    "critical": "🚨",
}


def generate_markdown_report(dataset: UploadedDataset) -> str:
    """Generate a Markdown privacy report for a scanned dataset."""
    now = timezone.now().strftime("%Y-%m-%d %H:%M UTC")
    band_label = RISK_BAND_LABELS.get(dataset.risk_band, dataset.risk_band)
    profiles = list(dataset.column_profiles.order_by("-risk_score"))
    findings = list(dataset.findings.order_by("-severity"))

    direct_id_cols = [p for p in profiles if p.privacy_category == "direct_identifier"]
    quasi_id_cols = [p for p in profiles if p.privacy_category == "quasi_identifier"]
    sensitive_cols = [p for p in profiles if p.privacy_category == "sensitive_attribute"]

    lines = [
        "# Privacy Review Report",
        "",
        f"**Dataset:** {dataset.original_filename}  ",
        f"**Organisation:** {dataset.organisation.name}  ",
        f"**Reviewed:** {now}  ",
        f"**Status:** {dataset.get_processing_status_display()}  ",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Rows | {dataset.row_count:,} |",
        f"| Columns | {dataset.column_count} |",
        f"| Privacy Risk Score | **{dataset.privacy_risk_score}/100** |",
        f"| Risk Band | {band_label} |",
        f"| Direct Identifiers | {len(direct_id_cols)} column(s) |",
        f"| Quasi-Identifiers | {len(quasi_id_cols)} column(s) |",
        f"| Sensitive Attributes | {len(sensitive_cols)} column(s) |",
        f"| Findings | {len(findings)} |",
        "",
        "---",
        "",
        "## Important Notice",
        "",
        (
            "> This report is generated by automated analysis and provides decision-support signals, "
            "not legal advice. All outputs require human verification before action is taken. "
            "Consult a qualified data protection officer for compliance decisions."
        ),
        "",
        "---",
        "",
        "## Privacy Findings",
        "",
    ]

    if not findings:
        lines.append("*No privacy findings detected.*")
    else:
        for i, f in enumerate(findings, 1):
            emoji = SEVERITY_EMOJI.get(f.severity, "•")
            lines += [
                f"### {i}. {emoji} {f.title}",
                "",
                f"**Severity:** {f.get_severity_display()}  ",
                f"**Confidence:** {f.confidence:.0%}  ",
                f"**Affected columns:** {', '.join(f.affected_columns) or '—'}  ",
                "",
                f"{f.description}",
                "",
                f"**Recommendation:** {f.recommendation}",
                "",
            ]

    lines += [
        "---",
        "",
        "## Column Profiles",
        "",
        "| Column | Inferred Type | Privacy Category | Uniqueness | Risk Score | Recommendation |",
        "|---|---|---|---|---|---|",
    ]

    for p in profiles:
        lines.append(
            f"| {p.column_name} | {p.get_inferred_type_display()} "
            f"| {p.get_privacy_category_display()} "
            f"| {p.uniqueness_ratio:.0%} "
            f"| {p.risk_score} "
            f"| {p.recommended_transformation} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Recommended Actions",
        "",
    ]

    recs = _collect_recommendations(findings)
    if recs:
        for rec in recs:
            lines.append(f"- {rec}")
    else:
        lines.append("*No specific actions required at this time.*")

    lines += [
        "",
        "---",
        "",
        "*Generated by CivicSec Lab — DataPrivacy Doctor. "
        "For internal use only. Do not distribute without review.*",
    ]

    return "\n".join(lines)


def _collect_recommendations(findings) -> list[str]:
    seen = set()
    recs = []
    for f in findings:
        rec = f.recommendation.strip()
        if rec and rec not in seen:
            seen.add(rec)
            recs.append(rec)
    return recs
