# Generated by Django 5.2.14 on 2026-05-14 11:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cve_id", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("product", models.CharField(blank=True, max_length=255)),
                ("date_added_to_kev", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("known_ransomware_campaign_use", models.BooleanField(default=False)),
                ("required_action", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("cwe", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cisa_kev", "CISA KEV"),
                            ("manual", "Manual"),
                            ("osv", "OSV"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["cve_id"],
                "indexes": [
                    models.Index(fields=["cve_id"], name="threatboard_cve_id_7578e4_idx"),
                    models.Index(fields=["vendor"], name="threatboard_vendor_a9e9de_idx"),
                    models.Index(fields=["product"], name="threatboard_product_754bd6_idx"),
                    models.Index(fields=["source"], name="threatboard_source_a19a36_idx"),
                    models.Index(
                        fields=["date_added_to_kev"], name="threatboard_date_ad_58308b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "epss_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "epss_percentile",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "cvss_severity",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("kev_known_exploited", models.BooleanField(default=False)),
                ("last_epss_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_scored_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="threatboard.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["vulnerability__cve_id"],
            },
        ),
        migrations.CreateModel(
            name="ThreatIngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("kev_ingestion", "KEV ingestion"),
                            ("epss_enrichment", "EPSS enrichment"),
                            ("asset_matching", "Asset matching"),
                            ("risk_scoring", "Risk scoring"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cisa_kev", "CISA KEV"),
                            ("first_epss", "FIRST EPSS"),
                            ("internal", "Internal"),
                            ("manual", "Manual"),
                        ],
                        default="internal",
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_seen", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threat_ingestion_runs",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["run_type", "status"], name="threatboard_run_typ_694a48_idx"
                    ),
                    models.Index(fields=["source"], name="threatboard_source_862888_idx"),
                    models.Index(
                        fields=["organisation", "run_type"], name="threatboard_organis_594103_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetVulnerabilityMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("exact_vendor_product", "Exact vendor/product"),
                            ("dependency_file", "Dependency file"),
                            ("manual", "Manual"),
                            ("keyword_match", "Keyword match"),
                            ("sbom_match", "SBOM match"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                (
                    "match_confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "exposure_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "calculated_risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dismissed", "Dismissed"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False positive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "remediation_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("affected", "Affected"),
                            ("not_affected", "Not affected"),
                            ("patched", "Patched"),
                            ("mitigated", "Mitigated"),
                            ("accepted_risk", "Accepted risk"),
                        ],
                        default="unreviewed",
                        max_length=30,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerability_matches",
                        to="assets.asset",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerability_matches",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_matches",
                        to="threatboard.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_risk_score", "asset__name", "vulnerability__cve_id"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "risk_band"], name="threatboard_organis_cf00f1_idx"
                    ),
                    models.Index(
                        fields=["organisation", "status"], name="threatboard_organis_ddda68_idx"
                    ),
                    models.Index(
                        fields=["remediation_status"], name="threatboard_remedia_138348_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "asset", "vulnerability"),
                        name="unique_asset_vulnerability_match",
                    )
                ],
            },
        ),
    ]
