# Generated by Django 5.2.14 on 2026-06-11 00:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_identifier", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login success"),
                            ("login_failed", "Login failed"),
                            ("logout", "Logout"),
                            ("password_reset", "Password reset"),
                            ("file_download", "File download"),
                            ("settings_change", "Settings change"),
                            ("mfa_challenge", "MFA challenge"),
                            ("mfa_failed", "MFA failed"),
                        ],
                        default="login_success",
                        max_length=30,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("resource_accessed", models.CharField(blank=True, max_length=255)),
                ("raw_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "upload_batch",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for the CSV upload batch this event came from.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LoginAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_identifier", models.CharField(max_length=255)),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("failed_login_burst", "Failed login burst"),
                            (
                                "suspicious_success_after_failures",
                                "Suspicious success after failures",
                            ),
                            ("impossible_travel", "Impossible travel"),
                            ("new_device", "New device"),
                            ("unusual_time", "Unusual time"),
                            ("sensitive_access_after_anomaly", "Sensitive access after anomaly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("mitre_tactic", models.CharField(blank=True, max_length=120)),
                ("mitre_technique", models.CharField(blank=True, max_length=120)),
                ("evidence_detail", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("escalated", "Escalated"),
                            ("dismissed", "Dismissed"),
                            ("false_positive", "False positive"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_anomalies",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "risk_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_anomalies",
                        to="risk.riskevent",
                    ),
                ),
                (
                    "linked_events",
                    models.ManyToManyField(
                        blank=True, related_name="anomalies", to="loglens.loginevent"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-risk_score"],
            },
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["organisation", "user_identifier", "timestamp"],
                name="loglens_log_organis_1934ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["organisation", "event_type", "timestamp"],
                name="loglens_log_organis_93baab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["organisation", "success", "timestamp"],
                name="loglens_log_organis_3fb029_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(fields=["upload_batch"], name="loglens_log_upload__2fc7ed_idx"),
        ),
        migrations.AddIndex(
            model_name="loginanomaly",
            index=models.Index(
                fields=["organisation", "anomaly_type", "status"],
                name="loglens_log_organis_5d9528_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginanomaly",
            index=models.Index(
                fields=["organisation", "severity"], name="loglens_log_organis_dc9584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginanomaly",
            index=models.Index(fields=["user_identifier"], name="loglens_log_user_id_8bb1f6_idx"),
        ),
    ]
